if(EXISTS "/home/nicholas/OperatingSystems/MultithreadWebserver/builds/tests/tests[1]_tests.cmake")
  include("/home/nicholas/OperatingSystems/MultithreadWebserver/builds/tests/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
